import puppeteer from 'puppeteer';
import {readFile,mkdir,writeFile} from 'node:fs/promises';
import assert from 'node:assert/strict';
await mkdir('output/playwright',{recursive:true});
const browser=await puppeteer.launch({headless:true,enableExtensions:true,pipe:true,args:['--autoplay-policy=no-user-gesture-required']});
const results=[];
try{
 const extensionID=await browser.installExtension(process.cwd());
 const ext=(await browser.extensions()).get(extensionID);
 assert(ext,'real extension loaded');
 const page=await browser.newPage();await page.setViewport({width:1200,height:700});
 await page.setRequestInterception(true);
 const clip=await readFile('tests/video.webm');
 page.on('request',r=>{if(r.url().endsWith('/fixture.webm'))r.respond({status:200,contentType:'video/webm',body:clip});else if(r.url().startsWith('https://www.youtube.com/'))r.respond({status:200,contentType:'text/html',body:'<!doctype html><html><head><title>Fillframe controlled fixture</title></head><body style="margin:0;background:#101012;color:white;font-family:system-ui"><h1 style="margin:24px;font-size:20px">Fillframe · controlled video fixture</h1><div id="movie_player" style="position:relative;width:1000px;height:428.571px;margin:24px;background:black;overflow:hidden"><video src="/fixture.webm" style="width:100%;height:100%;object-fit:contain" muted loop autoplay></video><div id="captions" style="position:absolute;bottom:10px;left:35%;font-size:24px">Captions stay readable</div></div></body></html>'});else r.abort();});
 await page.goto('https://www.youtube.com/fillframe-fixture');
 await page.waitForFunction(()=>document.querySelector('video')?.videoWidth===1280 && document.querySelector('[data-fillframe]'));
 const original=await page.$eval('video',v=>v.getAttribute('style'));
 const click=async id=>page.evaluate(id=>document.querySelector('[data-fillframe]').shadowRoot.querySelector(id).click(),id);
 await click('#toggle');
 await page.waitForFunction(()=>document.querySelector('video').style.width==='1000px');
 let rect=await page.$eval('video',v=>({w:v.getBoundingClientRect().width,h:v.getBoundingClientRect().height,top:parseFloat(v.style.top)}));
 assert(Math.abs(rect.w/rect.h-16/9)<.001);assert(rect.h>428);assert(rect.top<0);results.push('21:9 fill preserves ratio and crops top/bottom');
 await page.screenshot({path:'output/playwright/fill-wide.png'});
 await click('#more');await click('#remember');
 await page.reload();await page.waitForFunction(()=>document.querySelector('video')?.style.width==='1000px');results.push('remember persists across page reload');
 await page.$eval('#movie_player',el=>{el.style.width='800px';el.style.height='500px'});
 await page.waitForFunction(()=>Math.abs(parseFloat(document.querySelector('video').style.height)-500)<1);
 rect=await page.$eval('video',v=>({w:parseFloat(v.style.width),h:parseFloat(v.style.height)}));assert(Math.abs(rect.h-500)<1);results.push('16:10 resize crops left/right');
 await click('#toggle');await page.waitForFunction(()=>document.querySelector('video').style.width==='100%');
 const restored=await page.$eval('video',v=>v.getAttribute('style'));assert.equal(restored.replace(/[ ;]+$/,'').replaceAll(' ',''),original.replace(/[ ;]+$/,'').replaceAll(' ',''));results.push('Original restores owned inline properties');
 await click('#more');await click('#reset');
 await page.evaluate(()=>{const v=document.querySelector('video');const n=v.cloneNode();v.replaceWith(n)});
 await page.waitForFunction(()=>document.querySelector('video')?.videoWidth===1280);await click('#toggle');
 await page.waitForFunction(()=>parseFloat(document.querySelector('video').style.width)>880);results.push('replacement video reattaches controls');
 await click('#more');
 await page.evaluate(()=>{const e=document.querySelector('[data-fillframe]').shadowRoot.querySelector('#ratio');e.value='2.39';e.dispatchEvent(new Event('change'));});
 await page.waitForFunction(()=>parseFloat(document.querySelector('video').style.width)>1100);results.push('manual cinema ratio adds crop for encoded bars');
 await page.screenshot({path:'output/playwright/cinema-controls.png'});
 await page.bringToFront();
 await ext.triggerAction(page);
 const popupTarget=await browser.waitForTarget(t=>t.type()==='page'&&t.url().includes(extensionID)&&t.url().endsWith('popup.html'));
 const popup=await popupTarget.asPage();
 await popup.waitForFunction(()=>document.body.dataset.ready==='true');
 await popup.click('#original');await page.waitForFunction(()=>document.querySelector('video').style.width==='100%');
 await popup.click('#fill');await page.waitForFunction(()=>parseFloat(document.querySelector('video').style.width)>1100);
 await popup.emulateMediaFeatures([{name:'prefers-color-scheme',value:'dark'}]);
 await popup.screenshot({path:'output/playwright/popup-dark.png'});
 await popup.emulateMediaFeatures([{name:'prefers-color-scheme',value:'light'}]);
 await popup.screenshot({path:'output/playwright/popup-light.png'});
 await popup.click('#reset');await page.waitForFunction(()=>document.querySelector('video').style.width==='100%');
 results.push('actual extension popup connects, fills, restores and resets');
 await popup.click('#fill');
 await page.waitForFunction(()=>document.querySelector('video').style.getPropertyPriority('width')==='important');
 await page.$eval('video',v=>v.style.setProperty('width','777px'));
 await page.waitForFunction(()=>document.querySelector('video').style.getPropertyPriority('width')==='important');
 await popup.click('#original');
 await page.waitForFunction(()=>document.querySelector('video').style.width==='777px');
 results.push('Original preserves player changes made while fill was active');
 await popup.close();await page.bringToFront();
 await page.$eval('#movie_player',el=>{const bar=document.createElement('div');bar.className='ytp-right-controls-right';bar.innerHTML='<button class="ytp-fullscreen-button">Fullscreen</button>';el.append(bar);});
 await page.waitForSelector('[data-fillframe-toolbar]');
 await page.click('[data-fillframe-toolbar]');
 await page.waitForFunction(()=>document.querySelector('video').style.getPropertyPriority('width')==='important');
 assert(await page.evaluate(()=>document.querySelector('[data-fillframe]').shadowRoot.querySelector('#panel').hidden));
 assert(await page.$eval('[data-fillframe-toolbar]',b=>b.nextElementSibling.classList.contains('ytp-fullscreen-button')));
 results.push('native toolbar direct fill opens no controls');
 await page.click('[data-fillframe-toolbar]');
 await page.waitForFunction(()=>document.querySelector('video').style.width==='777px');
 await page.$eval('.ytp-right-controls-right',el=>el.replaceWith(el.cloneNode(true)));
 await page.waitForFunction(()=>document.querySelectorAll('[data-fillframe-toolbar]').length===1);
 results.push('toolbar toggle restores original and survives control replacement');
 await writeFile('output/playwright/results.json',JSON.stringify({browser:await browser.version(),results},null,2));console.log(results);
}catch(e){console.error(e);process.exitCode=1}finally{await browser.close()}
